// src/quotes/dailyQuotes.ts
// Deterministic daily quote per user (same quote for that user all day)
// Usage: getDailyQuote(userId, new Date())

export const QUOTES: string[] = [
  "Small steps every day create big change.",
  "Excellence is a habit you build today.",
  "Your future self is watching—impress them.",
  "Quality is the best business plan.",
  "Don't count hours; make hours count.",
  "Be so good they can't ignore you.",
  "Little progress adds up to big results.",
  "Every problem hides an opportunity.",
  "Energy and persistence conquer most things.",
  "Do it with passion or not at all.",
  "Your work is your signature—sign it well.",
  "Dream big. Start small. Move now.",
  "Hard work wins when talent rests.",
  "Guard your energy like a CEO.",
  "Momentum is magic—keep moving.",
  "Done beats perfect when perfect stalls.",
  "Excellence is a choice you renew.",
  "What you focus on expands.",
  "Don't wish. Work.",
  "Discipline beats motivation on tough days.",
  "Success is tiny efforts repeated.",
  "Today is another chance to get it right.",
  "Work smart, then work steady.",
  "Growth lives outside comfort.",
  "Make today your masterpiece.",
  "Stay hungry. Stay humble.",
  "Turn obstacles into stepping stones.",
  "Your energy speaks before you do.",
  "Push yourself—no one else will.",
  "Your best teacher is your last mistake.",
  "Consistency builds trust and results.",
  "Clarity creates speed.",
  "Progress > perfection.",
  "Little by little becomes a lot.",
  "Courage is a muscle—use it daily.",
  "Focus is a superpower.",
  "Start where you are, use what you have.",
  "Win the morning; win the day.",
  "People remember how you make them feel.",
  "Effort compounds—invest daily.",
  "Systems beat goals when it's busy.",
  "Raise the bar, then clear it.",
  "Preparation is quiet confidence.",
  "Action cures anxiety.",
  "Sharpen the axe before the swing.",
  "Feedback is data—use it.",
  "Be the calm in the chaos.",
  "Trust the process you're building.",
  "Your standards set your ceiling.",
  "You don't find time; you make it.",
  "Choices make habits; habits make outcomes.",
  "Move fast, don't rush.",
  "Be reliable; be remarkable.",
  "Work with intention, not tension.",
  "Small wins fuel big wins.",
  "Plan the work. Work the plan.",
  "What gets measured improves.",
  "Protect deep work time.",
  "Punctuality is professional respect.",
  "Own the result—good or bad.",
  "Stay curious longer.",
  "Underpromise. Overdeliver.",
  "Simplify until it sings.",
  "Craft beats speed when quality matters.",
  "Be useful every hour.",
  "Make it easy to do the right thing.",
  "Let the work speak.",
  "Bring solutions, not just problems.",
  "Talent is a gift; discipline is a choice.",
  "Your environment shapes your output.",
  "Say no to protect your best yes.",
  "Finish what you start.",
  "Accuracy is kindness to the next person.",
  "Details are where excellence hides.",
  "Build trust through consistency.",
  "Practice creates permanence.",
  "Your pace is fine—just don't stop.",
  "Be a thermostat, not a thermometer.",
  "Assume positive intent.",
  "Clutter steals clarity.",
  "If it takes two minutes, do it now.",
  "The standard is the standard.",
  "Own your calendar or it owns you.",
  "Make handoffs effortless.",
  "Start earlier than your excuses.",
  "If it's important, schedule it.",
  "Leaders go first.",
  "Respect deadlines—yours and theirs.",
  "Your name is on this—make it proud.",
  "Under pressure, breathe and execute.",
  "Preparation makes luck look normal.",
  "Show up ready, not just present.",
  "Be the person others can count on.",
  "Caring is a competitive advantage.",
  "We rise by lifting each other.",
  "Quality is everyone's job.",
  "Say it clearly. Say it once.",
  "Be brief. Be bright. Be gone.",
  "Results love routines.",
  "Today's habits write tomorrow's story.",
  "Keep promises to yourself first.",
  "Finish strong; future you will thank you.",
  "Repetition is the mother of skill.",
  "Make the hard thing the first thing.",
  "Progress is permission to continue.",
  "Ship it, then improve it.",
  "Respect the craft.",
  "Pride in the process, not just the product.",
  "Do less, but better.",
  "Think long-term; act short-term.",
  "Don't break the chain—show up daily.",
  "Effort leaves clues—make them obvious.",
  "Master the basics relentlessly.",
  "Be interested, not just interesting.",
  "Simplicity scales; complexity fails.",
  "Routine creates freedom.",
  "Curate your inputs to upgrade outputs.",
  "Make excellence your default setting.",
  "Urgency without panic.",
  "Stay a student.",
  "Be kind and exacting.",
  "Focus on what you can control.",
  "You get what you tolerate.",
  "Persistence rewrites the odds.",
  "If not you, who? If not now, when?",
  "Be your own competition.",
  "Great work requires great rest.",
  "Build bridges, not silos.",
  "Let your work ethic be loud.",
  "Outlearn, then outlast.",
  "Track it to improve it.",
  "Replace 'I have to' with 'I get to.'",
  "Grind with gratitude.",
  "Less talk, more craft.",
  "Make it unmistakably professional.",
  "Don't wing it—design it.",
  "Preparation is a kindness to your future self.",
  "Don't be busy; be effective.",
  "Every rep counts.",
  "The obstacle is the way.",
  "Be coachable.",
  "Rituals build results.",
  "Decisions define direction.",
  "Work your plan; trust your pace.",
  "Leave things better than you found them.",
  "Quality over clout.",
  "Don't confuse motion with progress.",
  "Clarity before speed.",
  "Calendars don't lie.",
  "Make feedback safe, fast, and normal.",
  "Document once, reuse often.",
  "Professionalism is a daily practice.",
  "Champions love the boring reps.",
  "Curiosity cracks problems open.",
  "Take notes like a pro.",
  "Communicate before it becomes urgent.",
  "Think in systems, act in steps.",
  "If it isn't scheduled, it's optional.",
  "Protect your focus like treasure.",
  "Say what you'll do, then do it.",
  "Make success easier than failure.",
  "Keep the bar high and reachable.",
  "Direction beats speed.",
  "What you repeat, you become.",
  "Trade complaints for commitments.",
  "Create more than you consume.",
  "Start now; refine later.",
  "Be allergic to excuses.",
  "Sweat the right details.",
  "Show receipts—measure results.",
  "Let excellence be your brand.",
  "Your habits are louder than your words.",
  "Be the reason the day goes smoother.",
  "Shorten the loop from idea to action.",
  "Good notes save future headaches.",
  "Lead with clarity and care.",
  "Make the invisible work visible.",
  "Mastery is built, not bought.",
  "Courage first; confidence next.",
  "Attention is your most valuable currency.",
  "Polish matters.",
  "Don't postpone difficult conversations.",
  "The standard you walk past is the standard you accept.",
  "Be precise with language and timelines.",
  "Ask better questions.",
  "Repeat what works.",
  "Don't take short cuts; take right cuts.",
  "Protect your mornings.",
  "Turn intent into appointments.",
  "Earn trust by keeping small promises.",
  "Clarity reduces conflict.",
  "Keep errors rare and shallow.",
  "Choose usefulness over ego.",
  "Sweat now so you don't bleed later.",
  "Make accountability your advantage.",
  "Think big, operate simple.",
  "Learn, apply, teach.",
  "When in doubt, simplify.",
  "Hold yourself to pro standards.",
  "Build momentum, not drama.",
  "Be timely. Be tidy. Be thorough.",
  "Ownership is magnetic.",
  "Turn pro in your mind first.",
  "Move like you mean it.",
  "Plan for reality, not fantasy.",
  "Default to action.",
  "Great teams communicate early.",
  "Design your day like a product.",
  "Keep learning in public.",
  "Less friction, more flow.",
  "Respect people's time like money.",
  "Be consistent more than intense.",
  "Decide, then commit.",
  "You can do hard things.",
  "Your craft deserves your best.",
  "Craft the experience, not just the output.",
  "Brains on, ego off.",
  "Let data guide, not dictate.",
  "Build trust faster than tasks.",
  "Make it robust, then make it pretty.",
  "Precision is speed in disguise.",
  "Take responsibility; take the lead.",
  "Keep your promises visible.",
  "Ask for clarity, not permission.",
  "Chase progress, not applause.",
  "Slow is smooth; smooth is fast.",
  "Give credit generously.",
  "Learn the why behind the what.",
  "The little things are the big things.",
  "Finish lines create liftoff.",
  "Keep scope tight; quality high.",
  "Schedule deep work, defend it.",
  "Communicate status before it's asked.",
  "Prepare twice; execute once.",
  "Make handoffs stupid simple.",
  "Every touchpoint is branding.",
  "Do it right when no one is watching.",
  "Lead yourself first.",
  "Use constraints to get creative.",
  "Adapt without losing standards.",
  "Show your work—transparency wins.",
  "Measure twice, click once.",
  "Be clear, be kind, be consistent.",
  "Keep momentum louder than moods.",
  "Mindset is infrastructure.",
  "Write it so future you understands.",
  "Be the adult in the room.",
  "We're not our feelings; we're our choices.",
  "Plan sprints; live sustainably.",
  "Less noise, more note-taking.",
  "Respect the queue—finish current, then next.",
  "Guardrails create freedom.",
  "Repeatability is a feature.",
  "Don't outsource your standards.",
  "Make the brief unmissable.",
  "Document the win so it can repeat.",
  "Fix root causes, not symptoms.",
  "Say no with a better yes.",
  "Protect brand and bandwidth.",
  "Keep meetings short and purposeful.",
  "Turn insights into SOPs.",
  "Teach what you just learned.",
  "Reset quickly after setbacks.",
  "Win the handoff; win the day.",
  "Do boring work beautifully.",
  "Stay visible. Stay valuable.",
  "Remove a blocker for someone today.",
  "Clarity is kindness.",
  "Treat every file like a client sees it.",
  "If it must be done, make it easy.",
  "Hard choices, easy life.",
  "Notes are a gift to your team.",
  "Don't break trust for speed.",
  "Your reputation arrives before you do.",
  "Build for the next person in the chain.",
  "Leave a trail of clarity.",
  "Take the initiative, not the credit.",
  "Your calm is contagious.",
  "Less perfection, more iteration.",
  "Protect the craft from the clock.",
  "Time on task beats talent at rest.",
  "Be the teammate you want to have.",
  "Make quality non-negotiable.",
  "Say exactly what you mean.",
  "Greatness is granular.",
  "Start ugly, end beautiful.",
  "Drafts are where magic begins.",
  "Be early. Be ready. Be respectful.",
  "Optimize for usefulness.",
  "Focus on inputs; honor the outcomes.",
  "Build the habit, then the speed.",
  "Lower the friction to start.",
  "Be outcome-oriented, process-proud.",
  "If it matters, write it down.",
  "Keep your tools tidy.",
  "A clear plan calms nerves.",
  "Chop the work into winnable pieces.",
  "Assumptions are expensive—verify.",
  "Be strict with standards, kind with people.",
  "Your word is a deliverable.",
  "Eliminate the unnecessary.",
  "Practice until calm under pressure.",
  "Work clean; think deeply.",
  "Think like an owner.",
  "Make excellence unavoidable.",
  "Show up like it's on purpose.",
  "Be the reason it shipped.",
  "Courage is a decision.",
  "Skill is earned in quiet hours.",
  "Routine your way to remarkable.",
  "Your habits hire your future.",
  "Keep faith with the process.",
  "Craft beats chaos.",
  "Take notes; take names; take action.",
  "Upgrade the system, not just the sprint.",
  "Communication is part of the craft.",
  "Treat time boxes like budgets.",
  "Make alignment before acceleration.",
  "Don't escalate—clarify.",
  "Fewer priorities, fuller progress.",
  "Protect quality at the edges.",
  "If you start, finish.",
  "Respect constraints; reveal creativity.",
  "You're closer than you think.",
  "Progress loves patience.",
  "Build things worth maintaining.",
  "Set the tone; set the pace.",
  "Process is the product behind the product.",
  "You can't rush mastery—show up daily.",
  "Make your future grateful.",
  "Write better checklists.",
  "Practice radical clarity.",
  "Be consistent with kindness.",
  "Let integrity lead.",
  "Sharpen skills in the quiet hours.",
  "Stack tiny wins.",
  "Craft the culture with your actions.",
  "A tidy workspace is a tidy mind.",
  "Your default becomes your destiny.",
  "Stop waiting—start building.",
  "When it's hard, lean in.",
  "Move with intent; finish with pride.",
  "You are responsible for the energy you bring.",
  "Never miss twice.",
  "Keep the main thing the main thing.",
  "Make momentum your manager.",
  "Own your Monday morning energy.",
  "Champions show up on tough days.",
  "Focus follows clarity of purpose.",
  "Your process is your competitive edge.",
  "Make today a small masterpiece.",
  "Build systems; trust the outcomes.",
  "Start where you are; improve where you can.",
  "Discipline is a decision renewed daily.",
  "Let excellence be your only option.",
  "Professional pride is quiet confidence.",
  "Create momentum with consistency.",
  "Your craft improves with focused practice.",
  "Be the person who gets things done.",
  "Quality is built through daily choices.",
  "Focus on progress, not perfection yet.",
  "Your energy is your most valuable resource.",
  "Make your future self proud today.",
  "Small efforts compound into big results.",
  "Every day is a chance to raise standards.",
  "Build trust through reliable execution.",
  "Your work ethic speaks louder than words.",
  "Make excellence your minimum standard.",
  "Focus creates breakthrough results.",
  "Professional habits create professional outcomes.",
  "Be the calm, steady presence others need.",
  "Your consistency builds others' confidence.",
  "Make every interaction count positively.",
  "Quality work is the best marketing.",
  "Build your reputation one task at a time.",
  "Excellence is a practice, not an accident.",
  "Your standards determine your ceiling.",
  "Make hard work look effortless through preparation.",
  "Be the person others can depend on completely.",
  "Your craft deserves your complete attention and care.",
];

/**
 * Get a deterministic daily quote for a user
 * Same user gets same quote all day, different quote each day
 */
export function getDailyQuote(userId: string, date: Date): string {
  // Create a date string (YYYY-MM-DD) to ensure same quote all day
  const dateString = date.toISOString().split('T')[0];
  
  // Combine userId and date for deterministic but varied selection
  const seed = `${userId}-${dateString}`;
  
  // Simple hash function for deterministic pseudo-randomness
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  
  // Ensure positive index
  const index = Math.abs(hash) % QUOTES.length;
  
  return QUOTES[index];
}

/**
 * Get current user's daily quote
 */
export function getCurrentDailyQuote(userId: string): string {
  return getDailyQuote(userId, new Date());
}